tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
2.154434690031884
loaded dataset:
/home/wecapstor1/caph/mppi045h/nuisance_summary/PKS_flare/HESS_public/dataset-simulated-2.154434690031884-hr.fits.gz
2.154434690031884
loaded dataset:
/home/wecapstor1/caph/mppi045h/nuisance_summary/PKS_flare/HESS_public/dataset-simulated-2.154434690031884-hr.fits.gz
Traceback (most recent call last):
  File "5_asimov_surface.py", line 113, in <module>
    dataset_asimov_N = Dataset_load.load_dataset_N(dataset_asimov_N, path,bkg_sys = False)        
  File "/home/wecapstor1/caph/mppi045h/nuisance_summary/Analysis/../Dataset_load.py", line 136, in load_dataset_N
    models_load = Models.read(path).copy()
  File "/home/wecapstor1/caph/mppi045h/gammapy/gammapy/modeling/models/core.py", line 436, in read
    yaml_str = make_path(filename).read_text()
  File "/home/wecapstor1/caph/mppi045h/anaconda3/envs/gammapy-dev/lib/python3.8/pathlib.py", line 1236, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/home/wecapstor1/caph/mppi045h/anaconda3/envs/gammapy-dev/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/home/wecapstor1/caph/mppi045h/anaconda3/envs/gammapy-dev/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '../Combined100_PKSflare_crab_cutoff/data/0_model_nui_livetime_2.154434690031884_np.yml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "5_asimov_surface.py", line 118, in <module>
    dataset_asimov_N = Dataset_load.load_dataset_N(dataset_asimov_N, path,bkg_sys = False)        
  File "/home/wecapstor1/caph/mppi045h/nuisance_summary/Analysis/../Dataset_load.py", line 136, in load_dataset_N
    models_load = Models.read(path).copy()
  File "/home/wecapstor1/caph/mppi045h/gammapy/gammapy/modeling/models/core.py", line 436, in read
    yaml_str = make_path(filename).read_text()
  File "/home/wecapstor1/caph/mppi045h/anaconda3/envs/gammapy-dev/lib/python3.8/pathlib.py", line 1236, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/home/wecapstor1/caph/mppi045h/anaconda3/envs/gammapy-dev/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/home/wecapstor1/caph/mppi045h/anaconda3/envs/gammapy-dev/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '../Combined100_PKSflare_crab_cutoff/data/0_model_nui_livetime_2.154434690031884_1000.yml'
Traceback (most recent call last):
  File "5_asimov_surface.py", line 113, in <module>
    dataset_asimov_N = Dataset_load.load_dataset_N(dataset_asimov_N, path,bkg_sys = False)        
  File "/home/wecapstor1/caph/mppi045h/nuisance_summary/Analysis/../Dataset_load.py", line 136, in load_dataset_N
    models_load = Models.read(path).copy()
  File "/home/wecapstor1/caph/mppi045h/gammapy/gammapy/modeling/models/core.py", line 436, in read
    yaml_str = make_path(filename).read_text()
  File "/home/wecapstor1/caph/mppi045h/anaconda3/envs/gammapy-dev/lib/python3.8/pathlib.py", line 1236, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/home/wecapstor1/caph/mppi045h/anaconda3/envs/gammapy-dev/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/home/wecapstor1/caph/mppi045h/anaconda3/envs/gammapy-dev/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '../Combined100_PKSflare_crab_cutoff/data/0_model_nui_livetime_2.154434690031884_np.yml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "5_asimov_surface.py", line 118, in <module>
    dataset_asimov_N = Dataset_load.load_dataset_N(dataset_asimov_N, path,bkg_sys = False)        
  File "/home/wecapstor1/caph/mppi045h/nuisance_summary/Analysis/../Dataset_load.py", line 136, in load_dataset_N
    models_load = Models.read(path).copy()
  File "/home/wecapstor1/caph/mppi045h/gammapy/gammapy/modeling/models/core.py", line 436, in read
    yaml_str = make_path(filename).read_text()
  File "/home/wecapstor1/caph/mppi045h/anaconda3/envs/gammapy-dev/lib/python3.8/pathlib.py", line 1236, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/home/wecapstor1/caph/mppi045h/anaconda3/envs/gammapy-dev/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/home/wecapstor1/caph/mppi045h/anaconda3/envs/gammapy-dev/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '../Combined100_PKSflare_crab_cutoff/data/0_model_nui_livetime_2.154434690031884_1000.yml'
srun: error: tf087: tasks 0-1: Exited with exit code 1
srun: Terminating StepId=433946.0
=== JOB_STATISTICS ===
=== current date     : Wed 13 Nov 2024 11:03:59 AM CET
= Job-ID             : 433946 on tinyfat
= Job-Name           : logfiles/5<
= Job-Command        : /home/wecapstor1/caph/mppi045h/nuisance_summary/Analysis/5.slurm
= Initial workdir    : /home/wecapstor1/caph/mppi045h/nuisance_summary/Analysis
= Queue/Partition    : work
= Slurm account      : caph with QOS=normal
= Requested resources:  for 1-00:00:00
= Elapsed runtime    : 00:02:31
= Total RAM usage    : 0.1 GiB of requested  GiB (%)   
= Node list          : tf087
= Subm/Elig/Start/End: 2024-11-13T11:01:27 / 2024-11-13T11:01:27 / 2024-11-13T11:01:28 / 2024-11-13T11:03:59
======================
=== Quota infos ======
    Path              Used     SoftQ    HardQ    Gracetime  Filec    FileQ    FiHaQ    FileGrace    
    /home/hpc           84.0G   104.9G   209.7G        N/A     171K     500K   1,000K        N/A    
    /home/saturn       963.0G     0.0K     0.0K        N/A  28,299                           N/A    
======================
